// Code generated by ts-translate. DO NOT EDIT.

package golang

import (
	_ "embed"
	"sync"

	ts "github.com/wow-look-at-my/go-tree-sitter"
)

//go:embed tables.zst
var tablesBlob []byte

func loadTables() *ts.Language {
	return ts.LoadGrammar("golang", tablesBlob, nil)
}

var language = sync.OnceValue(loadTables)

// Language returns the grammar, decoding its tables when a parse needs them.
func Language() *ts.Language { return language() }
